global_settings:
  cache_duration: 3600
  default_retry_attempts: 3
  default_timeout: 30
  enable_compression: true
  max_concurrent_sources: 10
  user_agent: StreamlineVPN/1.0.0
sources: !!python/object:streamline_vpn.core.source.manager._AwaitableList {}
