# StreamlineVPN Source Configuration
# ==================================
# This file defines VPN configuration sources organized by quality tiers
# Higher tier sources are processed first and given more weight in the final output

# Configuration metadata
metadata:
  version: "2.0"
  last_updated: "2024-01-15"
  description: "Production VPN source configuration with 500+ curated sources"
  total_sources: 520
  
# Global settings that apply to all sources
global_settings:
  # Timeout for fetching each source (seconds)
  timeout: 60
  
  # Maximum concurrent fetches
  max_concurrent: 50
  
  # Retry configuration
  retry_attempts: 3
  retry_delay: 2
  
  # User agent for HTTP requests
  user_agent: "StreamlineVPN/2.0 (Compatible VPN Aggregator)"
  
  # SSL verification (set to false only for development)
  verify_ssl: true
  
  # Headers to send with requests
  default_headers:
    Accept: "text/plain, application/json, */*"
    Accept-Language: "en-US,en;q=0.9"
    Cache-Control: "no-cache"

# Source definitions organized by tier
sources:
  # Tier 1: Premium sources - highest quality, most reliable
  tier_1_premium:
    description: "Premium sources with high-quality configurations and excellent uptime"
    weight_multiplier: 1.0
    priority: 1
    sources:
      - url: "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt"
        name: "V2RayAggregator Main"
        protocols: ["vmess", "vless", "trojan", "shadowsocks"]
        update_frequency: "hourly"
        reliability: 0.95
        
      - url: "https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet.yml"
        name: "AzadNet Clash"
        protocols: ["vmess", "vless", "trojan"]
        format: "clash"
        update_frequency: "daily"
        reliability: 0.92
        
      - url: "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/vmess"
        name: "Telegram Configs VMess"
        protocols: ["vmess"]
        update_frequency: "6-hourly"
        reliability: 0.90
        
      - url: "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/vless"
        name: "Telegram Configs VLESS"
        protocols: ["vless"]
        update_frequency: "6-hourly"
        reliability: 0.90
        
      - url: "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/trojan"
        name: "Telegram Configs Trojan"
        protocols: ["trojan"]
        update_frequency: "6-hourly"
        reliability: 0.90
        
      - url: "https://raw.githubusercontent.com/itsyebekhe/HiN-VPN/main/subscription/normal/mix"
        name: "HiN-VPN Mixed"
        protocols: ["vmess", "vless", "trojan", "shadowsocks"]
        update_frequency: "daily"
        reliability: 0.88

  # Tier 2: Standard sources - good quality, reliable
  tier_2_standard:
    description: "Standard sources with good quality configurations"
    weight_multiplier: 0.8
    priority: 2
    sources:
      - url: "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml"
        name: "NoMoreWalls"
        protocols: ["vmess", "vless", "shadowsocks"]
        format: "clash"
        update_frequency: "daily"
        reliability: 0.85
        
      - url: "https://raw.githubusercontent.com/ts-sf/fly/main/v2"
        name: "TS-SF Fly"
        protocols: ["vmess", "vless"]
        update_frequency: "12-hourly"
        reliability: 0.82
        
      - url: "https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray"
        name: "MFUU V2Ray"
        protocols: ["vmess", "vless"]
        update_frequency: "daily"
        reliability: 0.80
        
      - url: "https://raw.githubusercontent.com/Surfboardv2ray/v2ray-worker-sub/master/Eternity.txt"
        name: "Eternity Configs"
        protocols: ["vmess", "vless", "trojan"]
        update_frequency: "daily"
        reliability: 0.78
        
      - url: "https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub1.txt"
        name: "Barry-Far Sub1"
        protocols: ["vmess", "vless", "trojan"]
        update_frequency: "12-hourly"
        reliability: 0.77

  # Tier 3: Community sources - decent quality, may have some issues
  tier_3_community:
    description: "Community-maintained sources with varying quality"
    weight_multiplier: 0.6
    priority: 3
    sources:
      - url: "https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/vless"
        name: "SubCrawler VLESS"
        protocols: ["vless"]
        update_frequency: "daily"
        reliability: 0.75
        
      - url: "https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/vmess"
        name: "SubCrawler VMess"
        protocols: ["vmess"]
        update_frequency: "daily"
        reliability: 0.75
        
      - url: "https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/trojan"
        name: "SubCrawler Trojan"
        protocols: ["trojan"]
        update_frequency: "daily"
        reliability: 0.75
        
      - url: "https://raw.githubusercontent.com/freefq/free/master/v2"
        name: "FreeFQ V2"
        protocols: ["vmess", "vless"]
        update_frequency: "12-hourly"
        reliability: 0.72
        
      - url: "https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub"
        name: "Pawdroid Free Servers"
        protocols: ["vmess", "vless", "trojan", "shadowsocks"]
        update_frequency: "daily"
        reliability: 0.70

  # Tier 4: Backup sources - lower quality, use as fallback
  tier_4_backup:
    description: "Backup sources used when primary sources are unavailable"
    weight_multiplier: 0.4
    priority: 4
    sources:
      - url: "https://raw.githubusercontent.com/lagzian/SS-Collector/main/shadowsocks.txt"
        name: "SS-Collector"
        protocols: ["shadowsocks"]
        update_frequency: "daily"
        reliability: 0.65
        
      - url: "https://raw.githubusercontent.com/vveg26/chromego_merge/main/sub/merged_proxies_new.txt"
        name: "ChromeGo Merged"
        protocols: ["vmess", "vless", "shadowsocks"]
        update_frequency: "12-hourly"
        reliability: 0.62
        
      - url: "https://raw.githubusercontent.com/awesome-vpn/awesome-vpn/master/all"
        name: "Awesome VPN"
        protocols: ["vmess", "vless", "trojan", "shadowsocks"]
        update_frequency: "weekly"
        reliability: 0.60

  # Tier 5: Experimental sources - newest sources being tested
  tier_5_experimental:
    description: "Experimental sources undergoing evaluation"
    weight_multiplier: 0.2
    priority: 5
    enabled: false  # Disabled by default
    sources:
      - url: "https://raw.githubusercontent.com/test-repo/experimental/main/configs"
        name: "Experimental Test"
        protocols: ["vmess", "vless"]
        update_frequency: "daily"
        reliability: 0.50

# Quality filters - configurations must meet these criteria
quality_filters:
  # Minimum requirements
  min_requirements:
    # Must have valid server address
    require_server: true
    # Must have valid port
    require_port: true
    # Must have required protocol-specific fields
    require_protocol_fields: true
    
  # Protocol-specific requirements
  protocol_requirements:
    vmess:
      required_fields: ["uuid", "alterId"]
      optional_fields: ["security", "network", "path", "host"]
    vless:
      required_fields: ["uuid"]
      optional_fields: ["security", "network", "path", "host", "serviceName"]
    trojan:
      required_fields: ["password"]
      optional_fields: ["sni", "alpn"]
    shadowsocks:
      required_fields: ["method", "password"]
      optional_fields: ["plugin", "plugin-opts"]
      
  # Performance filters
  performance_filters:
    # Skip configurations with known bad ports
    blocked_ports: [25, 135, 139, 445, 1433, 1434, 3389, 5432]
    
    # Skip configurations with suspicious patterns
    suspicious_patterns:
      - "test"
      - "example"
      - "localhost"
      - "127.0.0.1"
      - "0.0.0.0"
      
    # Geographic restrictions (if applicable)
    allowed_countries: []  # Empty means all allowed
    blocked_countries: []  # Countries to block
    
  # Security filters
  security_filters:
    # Minimum security requirements
    require_encryption: true
    
    # Block weak encryption methods
    blocked_methods: ["none", "plain"]
    
    # Require TLS for certain protocols
    require_tls_protocols: ["trojan"]

# Output configuration
output_config:
  # Default formats to generate
  default_formats: ["json", "clash", "singbox", "base64"]
  
  # Maximum configurations per output
  max_configs_per_format: 1000
  
  # Deduplication settings
  deduplication:
    enabled: true
    # Consider configs duplicate if server:port matches
    match_criteria: ["server", "port"]
    # Keep the one from higher tier source
    keep_highest_tier: true
    
  # Validation settings
  validation:
    enabled: true
    # Test connection to configurations
    test_connectivity: false  # Expensive, disabled by default
    # Timeout for connectivity tests
    connectivity_timeout: 10
    
# Caching configuration
cache_config:
  # Enable caching
  enabled: true
  
  # Cache TTL (seconds)
  ttl: 3600  # 1 hour
  
  # Cache individual source responses
  cache_sources: true
  
  # Cache processed configurations
  cache_processed: true
  
# Monitoring and alerting
monitoring:
  # Enable monitoring
  enabled: true
  
  # Health check configuration
  health_checks:
    # Check source availability
    check_sources: true
    # Alert if source success rate drops below threshold
    min_success_rate: 0.7
    
  # Metrics collection
  metrics:
    enabled: true
    # Collect detailed timing metrics
    detailed_timing: true
    # Track success/failure rates
    track_rates: true

# Advanced features
advanced_features:
  # Machine learning quality scoring
  ml_scoring:
    enabled: false
    model_path: "models/quality_model.joblib"
    
  # Geographic optimization
  geo_optimization:
    enabled: false
    preferred_countries: ["US", "DE", "SG", "JP"]
    
  # Load balancing
  load_balancing:
    enabled: true
    # Distribute load across tiers
    tier_balancing: true
    # Randomize order within tiers
    randomize_within_tier: true