global_settings:
  cache_duration: 3600
  default_retry_attempts: 3
  default_timeout: 30
  enable_compression: true
  max_concurrent_sources: 10
  user_agent: StreamlineVPN/1.0.0
sources:
  - name: test_source
    type: subscription
    url: https://example.com/source.txt
