sources:
  tier_1_premium:
    description: High-quality, reliable sources with excellent uptime
    urls:
    - url: https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt
      weight: 0.9
      protocols:
      - vmess
      - vless
      - trojan
      update: 1h
      metadata:
        description: Premium source with high-quality configurations
        region: global
    - url: https://raw.githubusercontent.com/vveg26/get_proxy/main/dist/v2ray.config.txt
      weight: 0.85
      protocols:
      - vmess
      - vless
      update: 2h
      metadata:
        description: Reliable aggregator with good performance
        region: global
  tier_2_reliable:
    description: Trusted sources with good performance
    urls:
    - url: https://raw.githubusercontent.com/freefq/free/master/v2
      weight: 0.7
      protocols:
      - vmess
      - vless
      - trojan
      - ss
      update: 4h
      metadata:
        description: Free VPN configurations
        region: global
    - url: https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
      weight: 0.75
      protocols:
      - vmess
      - vless
      - trojan
      update: 6h
      metadata:
        description: SubCrawler aggregated sources
        region: global
    # Removed duplicates and placeholder example URLs
  tier_3_bulk:
    description: Bulk sources with many configurations
    urls:
    - url: https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
      weight: 0.6
      protocols:
      - vmess
      - vless
      - trojan
      - ss
      - ssr
      update: 12h
      metadata:
        description: Large collection of free nodes
        region: global
    - url: https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt
      weight: 0.5
      protocols:
      - vmess
      - vless
      - trojan
      - ss
      - ssr
      update: 12h
      metadata:
        description: NoMoreWalls aggregated sources
        region: global
processing:
  max_concurrent: 50
  timeout: 30
  retry_attempts: 3
  retry_delay: 2
quality:
  min_score: 0.3
  high_quality_threshold: 0.7
  blacklist_threshold: 0.1
output:
  formats:
  - raw
  - base64
  - json
  - csv
  - clash
  - singbox
  include_metadata: true
  sort_by_quality: true
cache:
  enabled: true
  ttl: 3600
  max_size: 1000
discovery:
  enabled: true
  interval: 6h
  platforms:
  - github
  - telegram
  max_new_sources: 50
