# StreamlineVPN Sources Configuration
metadata:
  version: "2.0"
  description: "Production VPN source configuration"
  last_updated: "2024-01-01"

global_settings:
  timeout: 30
  max_concurrent: 10
  retry_attempts: 3
  verify_ssl: true

sources:
  tier_1_premium:
    description: "High-quality premium sources"
    weight_multiplier: 1.0
    sources:
      - url: "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt"
        name: "V2RayAggregator Main"
        protocols: ["vmess", "vless", "trojan", "shadowsocks"]
        reliability: 0.95
      - url: "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt"
        name: "NoMoreWalls"
        protocols: ["vmess", "vless"]
        reliability: 0.90