apiVersion: v1
kind: Service
metadata:
  name: streamline-vpn-service
  namespace: streamline
  labels:
    app: streamline-vpn
spec:
  type: LoadBalancer
  selector:
    app: streamline-vpn
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8000
    protocol: TCP
    name: https
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
